# Generated by Django 6.0 on 2025-12-13 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PZKChairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('department', models.CharField(max_length=200, verbose_name='ПЦК')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название группы')),
                ('course', models.IntegerField(verbose_name='Курс')),
                ('specialty', models.CharField(max_length=200, verbose_name='Специальность')),
                ('start_year', models.IntegerField(verbose_name='Год начала обучения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название дисциплины')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Код МДК')),
                ('hours', models.IntegerField(verbose_name='Количество часов')),
                ('specialty', models.CharField(max_length=200, verbose_name='Специальность')),
                ('course', models.IntegerField(verbose_name='Курс')),
                ('has_exam', models.BooleanField(default=True, verbose_name='Есть экзамен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='TicketTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('header_template', models.TextField(verbose_name='Шапка билета')),
                ('footer_template', models.TextField(verbose_name='Подвал билета')),
                ('is_default', models.BooleanField(default=False, verbose_name='Шаблон по умолчанию')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Текст задания')),
                ('task_type', models.CharField(choices=[('oral', 'Устное'), ('practical', 'Практическое')], max_length=20, verbose_name='Тип задания')),
                ('course', models.IntegerField(verbose_name='Для курса')),
                ('difficulty', models.IntegerField(default=1, verbose_name='Сложность (1-5)')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tasks/', verbose_name='Файл с заданием')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tickets.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('department', models.CharField(max_length=200, verbose_name='Кафедра')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.IntegerField(verbose_name='Номер билета')),
                ('generation_date', models.DateTimeField(auto_now_add=True)),
                ('semester', models.IntegerField(default=5, verbose_name='Семестр')),
                ('chairman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.pzkchairman')),
                ('groups', models.ManyToManyField(to='tickets.studentgroup')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.teacher')),
            ],
            options={
                'ordering': ['ticket_number'],
            },
        ),
        migrations.CreateModel(
            name='TicketTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядковый номер в билете')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.task')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.generatedticket')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='generatedticket',
            name='tasks',
            field=models.ManyToManyField(through='tickets.TicketTask', to='tickets.task'),
        ),
    ]
