# Generated by Django 6.0 on 2026-03-16 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_generatedticket_teacher_alter_teacher_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeputyDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(default='Заместитель директора по УМР', max_length=200, verbose_name='Должность')),
                ('short_name', models.CharField(default='Конакина Е.Г.', max_length=50, verbose_name='Краткое имя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.AlterField(
            model_name='generatedticket',
            name='chairman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.pzkchairman', verbose_name='Председатель ПЦК'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Текст задания'),
        ),
        migrations.AddField(
            model_name='generatedticket',
            name='deputy_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.deputydirector', verbose_name='Зам. директора'),
        ),
        migrations.CreateModel(
            name='TaskImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500, verbose_name='Имя файла')),
                ('course', models.IntegerField(verbose_name='Курс')),
                ('task_type', models.CharField(choices=[('oral', 'Устное'), ('practical', 'Практическое')], max_length=20, verbose_name='Тип заданий')),
                ('imported_count', models.IntegerField(default=0, verbose_name='Импортировано заданий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.subject', verbose_name='Предмет')),
            ],
        ),
    ]
