# Generated by Django 6.0 on 2026-03-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_deputydirector_alter_generatedticket_chairman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskimportbatch',
            name='updated_count',
            field=models.IntegerField(default=0, verbose_name='Обновлено заданий'),
        ),
        migrations.AlterField(
            model_name='taskimportbatch',
            name='imported_count',
            field=models.IntegerField(default=0, verbose_name='Создано заданий'),
        ),
    ]
