# Generated by Django 6.0 on 2026-05-11 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_taskimportbatch_updated_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskimportbatch',
            options={'ordering': ['-created_at'], 'verbose_name': 'Импорт заданий', 'verbose_name_plural': 'Импорты заданий'},
        ),
        migrations.AlterField(
            model_name='taskimportbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата импорта'),
        ),
        migrations.AlterField(
            model_name='taskimportbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Импортировал'),
        ),
    ]
