# Generated by Django 6.0.5 on 2026-05-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_taskimportbatch_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedticket',
            name='teacher',
        ),
        migrations.AddField(
            model_name='generatedticket',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='tickets.teacher', verbose_name='Преподаватели'),
        ),
    ]
